#! /usr/bin/env bash

set -e

DIR_ROOT="$HOME/.papers_db"
DIR_DATA="$DIR_ROOT/data"
DIR_DATA_DOWNLOADS="$DIR_DATA/downloads"
DIR_DATA_PAPERS="$DIR_DATA/papers"
FILE_DB="$DIR_DATA/papers.db"


MD5SUM_CMD="md5sum"
if ! echo "foo" | $MD5SUM_CMD >/dev/null 2>&1; then
    MD5SUM_CMD=md5
fi


env_create() {
    mkdir -p "$DIR_ROOT"
    mkdir -p "$DIR_DATA"
    mkdir -p "$DIR_DATA_DOWNLOADS"
    mkdir -p "$DIR_DATA_PAPERS"
}

env_clean() {
    rm -rf "$DIR_DATA_DOWNLOADS"
}


die() {
    echo "$1"
    exit 1
}

md5cmd() {
    $MD5SUM_CMD "$1" | awk '{ print $1 }'
}

db() {
    sqlite3 "$FILE_DB" "$@"
}

init() {
    db 'CREATE TABLE papers (doc_id STRING PRIMARY KEY, path STRING)'
    db 'CREATE TABLE tags (tag STRING, doc_id STRING, PRIMARY KEY (tag, doc_id), FOREIGN KEY (doc_id) REFERENCES papers(doc_id))'
}

delete() {
    md5=$(md5cmd "$paper")
    db "DELETE FROM tags WHERE doc_id = \"$md5\""
    db "DELETE FROM papers WHERE doc_id = \"$md5\""
}

all_papers() {
    db "SELECT path FROM papers"
}

add() {
    paper="$1"
    [ -f "$paper" ] || die "$paper does not exist"
    md5=$(md5cmd "$paper")
    db "INSERT INTO papers (doc_id, path) VALUES(\"$md5\", \"$paper\")"
}

tag_add() {
    paper="$1"
    tag="$2"

    md5=$(md5cmd "$paper")

    db "INSERT INTO tags (tag, doc_id) VALUES (\"$tag\", \"$md5\")"
}

tag_show() {
    paper="$1"
    md5=$(md5cmd "$paper")
    db "SELECT tag FROM tags WHERE doc_id = \"$md5\""
}

tag_search() {
    arg=("$@")

    subselect=""
    if [ "$#" -gt "1" ]; then
    tag="${arg[1]}"
    subselect="SELECT doc_id FROM tags WHERE tag = \"$tag\""
    fi

    for ((i=2;i<=$1;i++)); do
    subselect=$subselect" INTERSECT SELECT doc_id FROM tags WHERE tag = \"${arg[i]}\""
    done

    select="SELECT path FROM papers WHERE doc_id IN ($subselect)"

    db "$select"
}

tag_all() {
    db "SELECT DISTINCT tag FROM tags"
}


dispatch() {
    case "$1" in
        "init")
            init
    ;;  "all")
            all_papers
    ;;  "add")
            shift
            paper="$1"
            add "$paper"
            shift
            for tag in "$@"; do
                tag_add "$paper" "$tag"
            done
    ;;  "add-from-url")
            shift
            tmpdir=$(mktemp -d "$DIR_DATA_DOWNLOADS"/file.XXX)
            pushd "$tmpdir"
            wget_status=$(wget "$1"; echo $?)
            file_name="$(ls)"
            popd
            if [ -f "$tmpdir/$file_name" -a "$wget_status" -eq 0 ]; then
                file_path_tmp="$tmpdir/$file_name"
                file_path_perm="$DIR_DATA_PAPERS/$file_name"
                mv "$file_path_tmp" "$file_path_perm"
                add "$file_path_perm"
                shift
                for tag in "$@"; do
                    tag_add "$file_path_perm" "$tag"
                done
            else
                echo "Failed to download"
            fi
    ;;  "tag-show")
            tag_show "$2"
    ;;  "tag-search")
            shift
            tag_search "$#" "$@"
    ;;  "tag-all")
            tag_all
    ;;  "tag-add")
            shift
            paper="$1"
            shift
            for tag in "$@"; do
                tag_add "$paper" "$tag"
            done
    ;;  *)
            echo "Unknown command: $1"
            exit 1
    esac
}


main() {
    trap env_clean EXIT
    env_create
    dispatch "$@"
}


main "$@"
